/*
 * IncFile1.h
 *
 * Created: 10/22/2020 12:58:39 AM
 *  Author: Kavish Ranawella
 */ 


#ifndef __error_H_
#define __error_H_

enum error {NO_ERROR,NULL_ERROR,PORT_ERROR,PIN_ERROR,PIN_NOT_SUPPORT,UNSUPPORTED_UART,UNSUPPORTED_BAUDRATE,UNSUPPORTED_FRAME_SIZE,DRIV_CALLBACK_MISSING,UART_ERROR_TX_BUSY,TX_ARRAY_ERROR,TX_ARRAY_LENGTH_ZERO_WARNING,APP_CALLBACK_MISSING,PACKET_BODY_LENGTH_ERROR};



#endif /* INCFILE1_H_ */